import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data: userSession } = useSession();

  return (
    <>
      <Head>
        <title>Twitter-Buns</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Hello there! My name is Farhana</h1>
        {userSession ? (
          <button onClick={() => void signOut()}>Sign Out</button>
        ) : (
          <button onClick={() => void signIn()}>Sign In</button>
        )}
      </div>
    </>
  );
};

export default Home;
